export {
  installWebMcpLoader,
  WEBMCP_APPROVAL_REQUEST_SCHEMA,
  WEBMCP_APPROVAL_SCHEMA,
  WEBMCP_SITE_MANIFEST_SCHEMA,
  WEBMCP_TOOL_CALL_SCHEMA,
  WEBMCP_TOOL_RESULT_SCHEMA
} from "./loader.js";
